name: Code Style
# Runs the check-format script from the repository.
# The used docker image contains all required tools at the correct version.
#
# See https://github.com/precice/ci-images
on:
  pull_request:
    paths:
      - '**.[ch]pp'
      - '**.[ch]'
      - '**.xml'

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: precice/ci-formatting:latest
    steps:
      - name: Checkout preCICE
        uses: actions/checkout@v3
      - name: Check formatting
        run: tools/formatting/check-format
